#!/bin/bash

# Pre-install script for nxsearch from NextControl

echo "Looking for old versions of NextControl..."

if [ -d "/var/log/nxcontrol" ]; then
    sudo rm -r /var/log/nxcontrol
    echo "Removed old logs files from NextControl"
fi

if [ -d "/etc/nxcontrol" ]; then
    sudo rm -r /etc/nxcontrol
    echo "Removed old configuration files from NextControl"
fi

if [ -f "/bin/nxsearch" ]; then
    sudo rm /bin/nxsearch
    echo "Removed old NextControl from /bin..."
fi

if [ -f "/usr/bin/nxsearch" ]; then
    sudo rm /usr/bin/nxsearch
    echo "Removed old NextControl from /usr/bin..."
fi

if [ -f "/usr/local/bin/nxsearch" ]; then
    sudo rm /usr/local/bin/nxsearch
    echo "Removed old symlink from /usr/local/bin..."
fi

exit 0;